export const mockIncomingPatients = [
  {
    id: "pt-14a",
    unitNumber: "Unit 14A",
    chiefComplaint: "Chest pain, possible STEMI",
    aiSummary:
      "Patient is a 62-year-old male with crushing chest pain, diaphoresis, hypotension, tachycardia, and low oxygen saturation. EMT reports likely STEMI activation and requests immediate cardiac evaluation.",
    vitals: {
      bloodPressure: "88/56",
      heartRate: 132,
      oxygenSaturation: "91%",
      respiratoryRate: 28,
    },
    etaMinutes: 7,
    locationLabel: "I-10 E near Arlington Ave",
    locationProgress: "3.2 miles out",
    severity: "Critical",
    specialties: ["Cardiac", "ICU"],
    routingStatus: "Incoming",
    transcriptSnippet:
      "Patient is pale, sweating, says chest pain started 30 minutes ago and is getting worse. Pressure is dropping.",
    transcriptMode: "Live transcript",
    confidence: 0.97,
    lastUpdated: "10:41 AM",
    severityReasoning: "Hypotension, tachycardia, low SpO2, and classic acute coronary syndrome symptoms indicate immediate cardiac threat.",
    demographics: "62M",
  },
  {
    id: "pt-22c",
    unitNumber: "Unit 22C",
    chiefComplaint: "Facial droop and slurred speech",
    aiSummary:
      "Patient is a 71-year-old female with sudden right-sided weakness, facial droop, and slurred speech. Last known well approximately 22 minutes ago. EMT suspects acute ischemic stroke.",
    vitals: {
      bloodPressure: "176/102",
      heartRate: 94,
      oxygenSaturation: "96%",
      respiratoryRate: 20,
    },
    etaMinutes: 9,
    locationLabel: "Venice Blvd and Robertson Blvd",
    locationProgress: "4.0 miles out",
    severity: "High",
    specialties: ["Stroke", "ICU"],
    routingStatus: "Accepted",
    transcriptSnippet:
      "Onset was sudden while eating breakfast, speech is garbled, right arm drift present, blood sugar normal.",
    transcriptMode: "AI-extracted from EMT voice",
    confidence: 0.93,
    lastUpdated: "10:39 AM",
    severityReasoning: "Time-sensitive neurologic deficits with recent onset make this a stroke-alert candidate.",
    demographics: "71F",
  },
  {
    id: "pt-31b",
    unitNumber: "Unit 31B",
    chiefComplaint: "Motorcycle trauma with abdominal tenderness",
    aiSummary:
      "Patient is a 27-year-old male involved in a high-speed motorcycle collision. Alert but increasingly restless with abdominal tenderness, left femur deformity, and probable internal bleeding.",
    vitals: {
      bloodPressure: "94/60",
      heartRate: 124,
      oxygenSaturation: "94%",
      respiratoryRate: 30,
    },
    etaMinutes: 6,
    locationLabel: "US-101 S near Silver Lake Blvd",
    locationProgress: "2.6 miles out",
    severity: "Critical",
    specialties: ["Trauma", "ICU"],
    routingStatus: "Preparing",
    transcriptSnippet:
      "Mechanism was high speed, helmet cracked, abdomen is rigid, left leg obviously deformed, pressure trending down.",
    transcriptMode: "AI-extracted from EMT voice",
    confidence: 0.95,
    lastUpdated: "10:42 AM",
    severityReasoning: "Mechanism of injury, hypotension trend, and abdominal findings suggest severe trauma requiring trauma bay activation.",
    demographics: "27M",
  },
  {
    id: "pt-18d",
    unitNumber: "Unit 18D",
    chiefComplaint: "Pediatric respiratory distress",
    aiSummary:
      "Patient is a 6-year-old child with severe wheezing, accessory muscle use, and limited response to initial albuterol treatment. Oxygen saturation remains borderline during transport.",
    vitals: {
      bloodPressure: "102/64",
      heartRate: 142,
      oxygenSaturation: "89%",
      respiratoryRate: 34,
    },
    etaMinutes: 11,
    locationLabel: "Wilshire Blvd near Western Ave",
    locationProgress: "5.8 miles out",
    severity: "High",
    specialties: ["Pediatrics", "ICU"],
    routingStatus: "Incoming",
    transcriptSnippet:
      "Child is working hard to breathe, tight wheezes throughout, sat dipped to 88 before nebulizer, mom reports asthma history.",
    transcriptMode: "AI-extracted from EMT voice",
    confidence: 0.91,
    lastUpdated: "10:37 AM",
    severityReasoning: "Pediatric hypoxia with ongoing respiratory distress requires rapid respiratory and pediatric support.",
    demographics: "6M",
  },
  {
    id: "pt-09f",
    unitNumber: "Unit 09F",
    chiefComplaint: "Third-trimester vaginal bleeding",
    aiSummary:
      "Patient is a 33-year-old pregnant female at 34 weeks with active vaginal bleeding and abdominal cramping. Hemodynamically stable for now but requires OB and neonatal readiness.",
    vitals: {
      bloodPressure: "108/70",
      heartRate: 118,
      oxygenSaturation: "98%",
      respiratoryRate: 22,
    },
    etaMinutes: 13,
    locationLabel: "Crenshaw Blvd and Slauson Ave",
    locationProgress: "7.1 miles out",
    severity: "Moderate",
    specialties: ["OB", "Pediatrics"],
    routingStatus: "Incoming",
    transcriptSnippet:
      "Thirty-four week pregnancy, bright red bleeding started 15 minutes ago, fetal movement still present, contractions irregular.",
    transcriptMode: "AI-extracted from EMT voice",
    confidence: 0.88,
    lastUpdated: "10:35 AM",
    severityReasoning: "Potential obstetric emergency with maternal tachycardia but currently stable airway and perfusion.",
    demographics: "33F",
  },
  {
    id: "pt-44k",
    unitNumber: "Unit 44K",
    chiefComplaint: "Partial thickness burn to arms and chest",
    aiSummary:
      "Patient is a 45-year-old kitchen worker with flash burns to bilateral forearms and anterior chest. Pain significant but airway intact and no soot seen in the mouth.",
    vitals: {
      bloodPressure: "128/82",
      heartRate: 110,
      oxygenSaturation: "99%",
      respiratoryRate: 18,
    },
    etaMinutes: 18,
    locationLabel: "Downtown LA Arts District",
    locationProgress: "9.4 miles out",
    severity: "Low",
    specialties: ["Burn"],
    routingStatus: "Rerouted",
    transcriptSnippet:
      "No hoarseness, no visible inhalation injury, burns are painful and blistering over chest and forearms, fluids started.",
    transcriptMode: "AI-extracted from EMT voice",
    confidence: 0.86,
    lastUpdated: "10:33 AM",
    severityReasoning: "Painful but stable burn case without airway compromise or shock indicators.",
    demographics: "45M",
  },
];

export const mockHospitalStatus = {
  availableBeds: 8,
  totalBeds: 24,
  waitTimeMinutes: 26,
  icuAvailability: 3,
  traumaBayAvailability: 1,
  routingStatus: "Open",
  manualOverrideActive: false,
  overrideReason: "",
};

export const mockSpecialties = [
  { key: "Trauma", label: "Trauma Bay", available: true, source: "Auto" },
  { key: "Stroke", label: "Stroke Center", available: true, source: "Auto" },
  { key: "Cardiac", label: "Cardiac Cath Lab", available: true, source: "Manual" },
  { key: "Pediatrics", label: "Pediatrics", available: true, source: "Auto" },
  { key: "ICU", label: "ICU Beds", available: true, source: "Auto" },
  { key: "Burn", label: "Burn Support", available: false, source: "Manual" },
  { key: "OB", label: "OB / L&D", available: true, source: "Auto" },
];
